baseURL: https://ospw.de
languageCode: en-us
title: "OSPW"

module:
  imports:
    - path: github.com/hugo-toha/toha/v4
  mounts:
    - source: static/files
      target: static/files
    - source: ./node_modules/flag-icons/flags
      target: static/flags
    - source: ./node_modules/@fontsource/mulish/files
      target: static/files
    - source: ./node_modules/katex/dist/fonts
      target: static/fonts

languages:
  en:
    languageCode: en
    languageName: English
    title: "OSPW"
    weight: 1

defaultContentLanguage: en

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

enableEmoji: false

params:
  author:
    name: "ospw"
  features:
    theme:
      enable: true
      services:
        light: true
        dark: true
        default: system
    portfolio:
      enable: true
    blog:
      enable: true
    notes:
      enable: true
  footer:
    enable: true
    template: footer.html
    navigation:
      enable: false
    contactMe:
      enable: false
    newsletter:
      enable: false
    credentials:
      enable: true
    disclaimer:
      enable: false
    copyright:
      enable: true
      text: "Â© 2026 ospw"
